version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
